name: 'Next.js cached build'
description: 'Build next.js app with cache'

inputs:
  build-command:
    description: 'Build command'
    required: true
    default: 'yarn web build'

  src-directory:
    description: 'Next.js project src absolute path'
    required: true
    default: 'packages/webapp/src'

  dist-directory:
    description: 'Next.js distribution absolute path'
    required: true
    default: 'packages/webapp/.next'

runs:
  using: 'composite'
  steps:
    - name: Get NodeJS Version
      id: node-version
      shell: bash
      run: echo "version=$(node --version)" >> $GITHUB_OUTPUT


    - name: Create next.js build cache
      uses: actions/cache@v3
      id: next-cache
      with:
        path: ${{ inputs.dist-directory }}
        key: ${{ runner.os }}-node@${{ steps.node-version.outputs.version }}-next-build-cache-${{ hashFiles(inputs.src-directory, '**/tsconfig.json')  }}

    - name: Build Next.js app
      if: steps.next-cache.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.build-command }}
