name: 'Setup project'
description: 'Setup frontend project environment'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: 'bash'